name: API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd health/API-Gateway/
            git pull
            docker compose down
            docker compose up -d
            cd ../Health-auth-service/
            docker compose down
            docker compose up -d
            cd ../Health-Analytics-service/
            docker compose down
            docker compose up -d
